######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 2 22:18:25 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += toggle-input.hh main-window.hh
SOURCES += main.cc toggle-input.cc main-window.cc
